from enum import Enum


class BuildType(Enum):
    NORMAL = 1
    DIFFBUILD = 2
    TESTS = 3
    OBJDIFFBUILD = 4
    BINARY_MATCHBUILD = 5


# ---------------------------------------------------------------------------
# Compiler / linker flags
# ---------------------------------------------------------------------------

base_flags = (
    "/MT /EHsc /G5 /Gs /GS /DNDEBUG /Zi /YX"
    " /I $builddir/autogenerated /I src /I 3rdparty/munit"
)

link_flags = (
    "/subsystem:windows /machine:X86 /filealign:4096"
    " /incremental:no /opt:ref /map /mapinfo:exports /mapinfo:lines"
    " /NODEFAULTLIB:libcpmt.lib"
)

link_libs = (
    "dinput8.lib dsound.lib d3d8.lib dxguid.lib d3dx8.lib winmm.lib"
    " kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib"
    " advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib"
    " odbc32.lib odbccp32.lib"
)

flags_per_buildtype = {
    BuildType.NORMAL:             "",
    BuildType.DIFFBUILD:          "/DDIFFBUILD",
    BuildType.TESTS:              "",
    BuildType.OBJDIFFBUILD:       "",
    BuildType.BINARY_MATCHBUILD:  "/DBINARYMATCHBUILD",
}

# Per-file codegen overrides (appended after the common cl_flags variable).
# Files not listed here get the default /Od /Oi /Ob1 /Op /Gy /GF flags.
_SMALL_CODEGEN = "/Os"           # adds size-optimisation on top of debug flags
_PBG3_FLAGS    = "/O2"           # full optimisation for the archive library


# ---------------------------------------------------------------------------
# Source lists
# (Link order matters for binary matching — do not reorder without good reason)
# ---------------------------------------------------------------------------

# Main game sources: name -> extra cl flags (empty string = use default)
# The dict order IS the link order.
cxx_sources = {
    # --- data/bss block 1: AsciiManager / Stage / EclManager cluster ---
    "AsciiManager":  "",
    "Stage":         "",
    "EclManager":    "",
    "EnemyEclInstr": "",
    "EffectManager": "",
    "Ending":        "",
    "EnemyManager":  "",
    "BulletManager": "",
    "Gui":           _SMALL_CODEGEN,
    "GameManager":   _SMALL_CODEGEN,
    "Global":        "",
    "TextHelper":    _SMALL_CODEGEN,
    "ItemManager":   "",
    "main":          "",
    "GameWindow":    "",
    "MidiOutput":    "",
    "Supervisor":    _SMALL_CODEGEN,
    "MusicRoom":     _SMALL_CODEGEN,
    "Player":        "",
    "ReplayManager": "",
    "ResultScreen":  _SMALL_CODEGEN,
    "ScreenEffect":  "",
    "SoundPlayer":   "",
    "AnmManager":    "",
    "MainMenu":      _SMALL_CODEGEN,
    "zwave":         "",
    "stubs":         "",
    # --- data/bss block 2: BombData / BulletData must stay at the tail ---
    "BombData":      "",
    "BulletData":    "",
}

# Pbg3 archive library (compiled with full optimisation, linked after game objs)
pbg3_sources = {
    "IPbg3Parser":    _PBG3_FLAGS,
    "Pbg3Parser":     _PBG3_FLAGS,
    "Pbg3Archive":    _PBG3_FLAGS,
    "FileAbstraction": _PBG3_FLAGS,
}

# Unit-test infrastructure
munit_sources = ["munit"]

test_sources = [
    "tests",
    "test_Pbg3Archive",
]
