import json
from pathlib import Path
from os.path import basename, splitext

from ninja_syntax import Writer

from compile_info import (
    BuildType,
    base_flags,
    link_flags,
    link_libs,
    flags_per_buildtype,
    cxx_sources,
    pbg3_sources,
    munit_sources,
    test_sources,
)

SCRIPTS_DIR = Path(__file__).parent


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _obj(name: str) -> str:
    """Return the build-dir-relative .obj path for a bare source name."""
    return "$builddir/" + name + ".obj"


def _objdiff(name: str) -> str:
    return "$builddir/objdiff/reimpl/" + name + ".obj"


# ---------------------------------------------------------------------------
# Variables
# ---------------------------------------------------------------------------

def configure_vars(writer: Writer, build_type: BuildType) -> None:
    writer.variable("ninja_required_version", "1.5")
    writer.variable("builddir", "build")
    writer.variable("cl", "cl.exe")
    writer.variable("rc", "rc.exe")
    writer.variable("link", "link.exe")

    extra = flags_per_buildtype[build_type]
    cl_common = base_flags + (" " + extra if extra else "")
    writer.variable("cl_common_flags", cl_common)

    # Default per-TU flags (debug / match build)
    writer.variable("cl_flags", "$cl_common_flags /Od /Oi /Ob1 /Op /Gy /GF")
    writer.variable("link_flags", link_flags)

    writer.variable("msvc_deps_prefix", "Note: including file:")


# ---------------------------------------------------------------------------
# Rules
# ---------------------------------------------------------------------------

def configure_rules(writer: Writer) -> None:
    writer.rule(
        "cc",
        "$cl /nologo /showIncludes $cl_flags $extra_cl_flags /c $in /Fd$out.pdb /Fo$out",
        deps="msvc",
    )
    writer.rule("genglobals", "python scripts/generate_globals.py $in $out")
    writer.rule("rc", "$rc /fo $out $in")
    writer.rule(
        "link",
        "$link $link_flags /nologo /out:$out $link_libs $in",
    )
    writer.rule(
        "copyicon",
        'python -c "import shutil; import sys; shutil.copyfile(sys.argv[1], sys.argv[2])" $in $out',
    )
    writer.rule("extracticon", "python scripts/extract_icon.py --output $out")
    writer.rule("geni18n", "python scripts/generate_i18n.py $in $out")

    writer.rule("gendef", "python scripts/gendef.py --output $out $in")
    writer.rule("rename_symbols", "python scripts/generate_objdiff_objs.py $in")


# ---------------------------------------------------------------------------
# Build statements
# ---------------------------------------------------------------------------

def configure_build(writer: Writer, build_type: BuildType) -> None:
    # --- generated headers ---
    writer.build("$builddir/autogenerated/i18n.hpp", "geni18n", "src/i18n.tpl")

    # --- icon ---
    if build_type == BuildType.BINARY_MATCHBUILD:
        writer.build("resources/original.ico", "extracticon")
        writer.build("$builddir/icon.ico", "copyicon", "resources/original.ico",
                     implicit="resources/original.ico")
    else:
        writer.build("$builddir/icon.ico", "copyicon", "resources/placeholder.ico")

    writer.build("$builddir/th06.res", "rc",
                 inputs="resources/th06.rc", implicit="$builddir/icon.ico")



    # --- globals ---
    writer.build("$builddir/globals.obj", "genglobals",
                 inputs="config/globals.csv", implicit=["scripts/generate_globals.py"])

    # --- game sources ---
    game_objs = []
    for name, extra_flags in cxx_sources.items():
        src = "src/" + name + ".cpp"
        out = _obj(name)
        vars_ = {"extra_cl_flags": extra_flags} if extra_flags else {}
        writer.build(
            out, "cc", src,
            implicit=["$builddir/autogenerated/i18n.hpp"],
            variables=vars_,
        )
        writer.build(_objdiff(name), "rename_symbols", out,
                     implicit=["scripts/generate_objdiff_objs.py"])
        game_objs.append(out)

    # --- pbg3 library sources ---
    pbg3_objs = []
    for name, extra_flags in pbg3_sources.items():
        src = "src/pbg3/" + name + ".cpp"
        out = _obj(name)
        writer.build(
            out, "cc", src,
            implicit=["$builddir/autogenerated/i18n.hpp"],
            variables={"extra_cl_flags": extra_flags},
        )
        writer.build(_objdiff(name), "rename_symbols", out,
                     implicit=["scripts/generate_objdiff_objs.py"])
        pbg3_objs.append(out)

    # --- munit ---
    munit_objs = []
    for name in munit_sources:
        out = _obj(name)
        writer.build(out, "cc", "3rdparty/munit/" + name + ".c")
        munit_objs.append(out)

    # --- test sources ---
    test_objs = []
    for name in test_sources:
        out = _obj(name)
        writer.build(out, "cc", "tests/" + name + ".cpp")
        test_objs.append(out)

    # --- objdiff phony ---
    with open("objdiff.json") as f:
        objdiff_json = json.load(f)
    objdiff_deps = []
    for obj in objdiff_json.get("objects", {}):
        objdiff_deps.append(obj["base_path"].replace("build", "$builddir"))
    for obj in objdiff_json.get("units", {}):
        objdiff_deps.append(obj["base_path"].replace("build", "$builddir"))
    writer.build("objdiff", "phony", [], objdiff_deps)

    # --- .def file ---
    all_src_objs = game_objs + pbg3_objs
    writer.build(
        "$builddir/th06.def", "gendef",
        inputs=all_src_objs,
        implicit=["scripts/gendef.py"],
    )

    # --- main executable ---
    exe_objs = game_objs + pbg3_objs + ["$builddir/th06.res"]
    if build_type == BuildType.DIFFBUILD:
        exe_objs += [_obj("globals")]

    writer.build(
        "$builddir/th06.exe", "link",
        inputs=exe_objs,
        variables={
            "link_libs": link_libs,
            "link_flags": "$link_flags /debug /pdb:$builddir/th06.pdb",
        },
    )

    # --- test executable ---
    writer.build(
        "$builddir/munit.lib", "link",
        inputs=munit_objs,
        variables={"link_flags": "/lib", "link_libs": ""},
    )
    writer.build(
        "$builddir/th06-tests.exe", "link",
        inputs=game_objs + pbg3_objs + test_objs + ["$builddir/munit.lib"],
        variables={
            "link_libs": link_libs + " $builddir/munit.lib",
            "link_flags": "/debug /pdb:$builddir/th06.pdb",
        },
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def configure(build_type: BuildType = BuildType.NORMAL) -> None:
    with (SCRIPTS_DIR.parent / "build.ninja").open("w") as f:
        writer = Writer(f, width=120)
        configure_vars(writer, build_type)
        configure_rules(writer)
        configure_build(writer, build_type)
        writer.close()


if __name__ == "__main__":
    configure(BuildType.NORMAL)
