; Listing generated by Microsoft (R) Optimizing Compiler Version 13.00.9466 

	TITLE	scratch/test_padding.cpp
	.386P
include listing.inc
if @Version gt 510
.model FLAT
else
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
_BSS	SEGMENT DWORD USE32 PUBLIC 'BSS'
_BSS	ENDS
$$SYMBOLS	SEGMENT BYTE USE32 'DEBSYM'
$$SYMBOLS	ENDS
_TLS	SEGMENT DWORD USE32 PUBLIC 'TLS'
_TLS	ENDS
;	COMDAT ?InlineFunc@@YAXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
FLAT	GROUP _DATA, CONST, _BSS
	ASSUME	CS: FLAT, DS: FLAT, SS: FLAT
endif

INCLUDELIB LIBC
INCLUDELIB OLDNAMES

PUBLIC	?TestFunc@@YAXXZ				; TestFunc
EXTRN	?NonInlineFunc@@YAXXZ:NEAR			; NonInlineFunc
; Function compile flags: /Odt
; File z:\users\main\untitled\scratch\test_padding.cpp
_TEXT	SEGMENT
_i$601 = -4
?TestFunc@@YAXXZ PROC NEAR				; TestFunc

; 9    : void TestFunc() {

  00000	55		 push	 ebp
  00001	8b ec		 mov	 ebp, esp
  00003	51		 push	 ecx

; 10   :     for (int i = 0; i < 10; i++) {

  00004	c7 45 fc 00 00
	00 00		 mov	 DWORD PTR _i$601[ebp], 0
  0000b	eb 09		 jmp	 SHORT $L602
$L603:
  0000d	8b 45 fc	 mov	 eax, DWORD PTR _i$601[ebp]
  00010	83 c0 01	 add	 eax, 1
  00013	89 45 fc	 mov	 DWORD PTR _i$601[ebp], eax
$L602:
  00016	83 7d fc 0a	 cmp	 DWORD PTR _i$601[ebp], 10 ; 0000000aH
  0001a	7d 07		 jge	 SHORT $L600

; 11   :         InlineFunc();

  0001c	e8 00 00 00 00	 call	 ?NonInlineFunc@@YAXXZ	; NonInlineFunc

; 12   :     }

  00021	eb ea		 jmp	 SHORT $L603
$L600:

; 13   : }

  00023	8b e5		 mov	 esp, ebp
  00025	5d		 pop	 ebp
  00026	c3		 ret	 0
?TestFunc@@YAXXZ ENDP					; TestFunc
_TEXT	ENDS
END
