; Listing generated by Microsoft (R) Optimizing Compiler Version 13.00.9466 

	TITLE	scratch/test_inline_multiple.cpp
	.386P
include listing.inc
if @Version gt 510
.model FLAT
else
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
_BSS	SEGMENT DWORD USE32 PUBLIC 'BSS'
_BSS	ENDS
$$SYMBOLS	SEGMENT BYTE USE32 'DEBSYM'
$$SYMBOLS	ENDS
_TLS	SEGMENT DWORD USE32 PUBLIC 'TLS'
_TLS	ENDS
;	COMDAT ?InlineWithVar@@YAXXZ
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
FLAT	GROUP _DATA, CONST, _BSS
	ASSUME	CS: FLAT, DS: FLAT, SS: FLAT
endif

INCLUDELIB LIBC
INCLUDELIB OLDNAMES

PUBLIC	?TestFuncMultiple@@YAXXZ			; TestFuncMultiple
EXTRN	?CallMe@@YAXXZ:NEAR				; CallMe
; Function compile flags: /Odt
; File z:\users\main\untitled\scratch\test_inline_multiple.cpp
_TEXT	SEGMENT
?TestFuncMultiple@@YAXXZ PROC NEAR			; TestFuncMultiple

; 10   : void TestFuncMultiple() {

  00000	55		 push	 ebp
  00001	8b ec		 mov	 ebp, esp
  00003	83 ec 30	 sub	 esp, 48			; 00000030H

; 11   :     InlineWithVar();

  00006	e8 00 00 00 00	 call	 ?CallMe@@YAXXZ		; CallMe

; 12   :     InlineWithVar();

  0000b	e8 00 00 00 00	 call	 ?CallMe@@YAXXZ		; CallMe

; 13   :     InlineWithVar();

  00010	e8 00 00 00 00	 call	 ?CallMe@@YAXXZ		; CallMe

; 14   : }

  00015	8b e5		 mov	 esp, ebp
  00017	5d		 pop	 ebp
  00018	c3		 ret	 0
?TestFuncMultiple@@YAXXZ ENDP				; TestFuncMultiple
_TEXT	ENDS
END
