; Listing generated by Microsoft (R) Optimizing Compiler Version 13.00.9466 

	TITLE	scratch/test_scope_reuse.cpp
	.386P
include listing.inc
if @Version gt 510
.model FLAT
else
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
_BSS	SEGMENT DWORD USE32 PUBLIC 'BSS'
_BSS	ENDS
$$SYMBOLS	SEGMENT BYTE USE32 'DEBSYM'
$$SYMBOLS	ENDS
_TLS	SEGMENT DWORD USE32 PUBLIC 'TLS'
_TLS	ENDS
FLAT	GROUP _DATA, CONST, _BSS
	ASSUME	CS: FLAT, DS: FLAT, SS: FLAT
endif

INCLUDELIB LIBC
INCLUDELIB OLDNAMES

PUBLIC	?ScopeReuseNoCall@@YAXXZ			; ScopeReuseNoCall
; Function compile flags: /Odt
; File z:\users\main\untitled\scratch\test_scope_reuse.cpp
_TEXT	SEGMENT
?ScopeReuseNoCall@@YAXXZ PROC NEAR			; ScopeReuseNoCall

; 5    : void ScopeReuseNoCall() {

  00000	55		 push	 ebp
  00001	8b ec		 mov	 ebp, esp
  00003	83 ec 30	 sub	 esp, 48			; 00000030H

; 6    :     { int a[4]; }
; 7    :     { int b[4]; }
; 8    :     { int c[4]; }
; 9    : }

  00006	8b e5		 mov	 esp, ebp
  00008	5d		 pop	 ebp
  00009	c3		 ret	 0
?ScopeReuseNoCall@@YAXXZ ENDP				; ScopeReuseNoCall
_TEXT	ENDS
PUBLIC	?ScopeReuseWithCall@@YAXXZ			; ScopeReuseWithCall
EXTRN	?CallMe@@YAXXZ:NEAR				; CallMe
; Function compile flags: /Odt
_TEXT	SEGMENT
?ScopeReuseWithCall@@YAXXZ PROC NEAR			; ScopeReuseWithCall

; 11   : void ScopeReuseWithCall() {

  0000a	55		 push	 ebp
  0000b	8b ec		 mov	 ebp, esp
  0000d	83 ec 30	 sub	 esp, 48			; 00000030H

; 12   :     { int a[4]; }
; 13   :     { int b[4]; }
; 14   :     CallMe();

  00010	e8 00 00 00 00	 call	 ?CallMe@@YAXXZ		; CallMe

; 15   :     { int c[4]; }
; 16   : }

  00015	8b e5		 mov	 esp, ebp
  00017	5d		 pop	 ebp
  00018	c3		 ret	 0
?ScopeReuseWithCall@@YAXXZ ENDP				; ScopeReuseWithCall
_TEXT	ENDS
PUBLIC	?ScopeReuseWithCallInside@@YAXXZ		; ScopeReuseWithCallInside
; Function compile flags: /Odt
_TEXT	SEGMENT
?ScopeReuseWithCallInside@@YAXXZ PROC NEAR		; ScopeReuseWithCallInside

; 18   : void ScopeReuseWithCallInside() {

  00019	55		 push	 ebp
  0001a	8b ec		 mov	 ebp, esp
  0001c	83 ec 30	 sub	 esp, 48			; 00000030H

; 19   :     { int a[4]; }
; 20   :     { int b[4]; CallMe(); }

  0001f	e8 00 00 00 00	 call	 ?CallMe@@YAXXZ		; CallMe

; 21   :     { int c[4]; }
; 22   : }

  00024	8b e5		 mov	 esp, ebp
  00026	5d		 pop	 ebp
  00027	c3		 ret	 0
?ScopeReuseWithCallInside@@YAXXZ ENDP			; ScopeReuseWithCallInside
_TEXT	ENDS
END
